Get http://localhost:3001/todos

###
POST http://localhost:3001/todo/new HTTP/1.1
Content-Type: application/json

{
	"text":"try 3"
}

###
DELETE http://localhost:3001/todo/delete/622ca2847ef0fa5b43ed45e6

###

PUT http://localhost:3001/todo/done/622c9f66fe4a7c62671116ef